name: clang-format Lint

on: [push]
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: DoozyX/clang-format-lint-action@v0.5
        with: 
          source: .
          extensions: 'h,cpp,c'
          clangFormatVersion: 9
