name: Unit Tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install papi
        run: sudo apt install libpapi-dev
        shell: bash 
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set vcpkg's response file path used as part of cache's key.
        env:
          vcpkgResponseFile: ${{github.workspace}}/scripts/vcpkg.txt
        run: |
          echo "::set-env name=vcpkgResponseFile::$vcpkgResponseFile"
        shell: bash
      - name: Cache vcpkg artifacts
        uses: actions/cache@v1
        with:
          path: ${{github.workspace}}/vcpkg
          key: ${{ hashFiles( env.vcpkgResponseFile ) }}-${{ hashFiles('.git/modules/vcpkg/HEAD') }}
      - name: dir
        run: find ${{ runner.workspace }}
      - name: Run vcpkg
        uses: lukka/run-vcpkg@v0
        id: runvcpkg
        with:
          vcpkgArguments: '@${{ env.vcpkgResponseFile }}'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
      - name: Run CMake with Ninja
        uses: lukka/run-cmake@v0
        id: runcmake
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: '-- -v'
      - name: Prints output of run-vcpkg's task
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_TRIPLET_OUT }}' "
      - name: clean vcpkg artifact that must not be cached
        run: |
          rm -rfv ${{ github.workspace }}/vcpkg/buildtrees
          rm -rfv ${{ github.workspace }}/vcpkg/packages
          rm -rfv ${{ github.workspace }}/vcpkg/downloads
        shell: bash
      - name: dir
        run: find ${{ runner.workspace }}