name: Unit Tests
on: [pull_request]

jobs:
  Debug:
    name: 'Debug tests'
    runs-on: ubuntu-18.04
    steps:
      - name: Install dependencies
        run: sudo apt install libpapi-dev clang-tidy-9
        shell: bash
      - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Restore artifacts, or setup vcpkg
        uses: lukka/run-vcpkg@v6
        id: runvcpkg
        with:
          setupOnly: false
          appendedCacheKey: ${{ hashFiles( '${{ github.workspace }}/vcpkg.txt' ) }}
          vcpkgArguments: '@${{ github.workspace }}/vcpkg.txt'
      - name: Run CMake with Ninja
        env:
          CC: clang-9
          CXX: clang++-9
          LDFLAGS: -fuse-ld=lld-9
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: "${{ github.workspace }}/CMakeLists.txt"
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: '-- -v'
          buildDirectory: ${{github.workspace}}/build
          cmakeAppendedArgs: "-DENABLE_LINTER=ON -DCMAKE_BUILD_TYPE=Debug"
      - name: Run ctest
        run: ctest
        shell: bash
        working-directory: ${{github.workspace}}/build
